version: '3.8'

services:
  # Backend API Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: expense-tracker-server
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
    env_file:
      - ./server/.env
    volumes:
      - ./server/credentials.json:/app/credentials.json:ro
      - ./server/token.json:/app/token.json
    networks:
      - expense-tracker-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:4000/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: expense-tracker-client
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:4000
    env_file:
      - ./client/.env
    depends_on:
      server:
        condition: service_healthy
    networks:
      - expense-tracker-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  expense-tracker-network:
    driver: bridge

volumes:
  server-data:

