name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  # Lint and Test Server
  server-lint-test:
    name: Server - Lint & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: server/package-lock.json

      - name: Install dependencies
        working-directory: ./server
        run: npm ci

      - name: Run linter
        working-directory: ./server
        run: npm run lint

      - name: Run tests
        working-directory: ./server
        run: npm test || echo "No tests specified"

  # Lint and Test Client
  client-lint-test:
    name: Client - Lint & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies
        working-directory: ./client
        run: npm ci

      - name: Run linter
        working-directory: ./client
        run: npm run lint

      - name: Run tests
        working-directory: ./client
        run: npm test -- --watchAll=false --passWithNoTests

      - name: Build client
        working-directory: ./client
        run: npm run build

  # Build Docker Images
  docker-build:
    name: Docker - Build Images
    runs-on: ubuntu-latest
    needs: [server-lint-test, client-lint-test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build server image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile
          push: false
          tags: expense-tracker-server:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build client image
        uses: docker/build-push-action@v5
        with:
          context: ./client
          file: ./client/Dockerfile
          push: false
          tags: expense-tracker-client:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Security Audit
  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Audit server dependencies
        working-directory: ./server
        run: npm audit --audit-level=moderate || true

      - name: Audit client dependencies
        working-directory: ./client
        run: npm audit --audit-level=moderate || true
