name: Build Docker Image and Commit Artifact

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -f server/Dockerfile -t my-node-app:latest ./server
          mkdir -p build
          docker save my-node-app:latest -o build/my-node-app.tar

      - name: Commit Docker image tarball
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add build/my-node-app.tar
          git commit -m "Add Docker image artifact [skip ci]" || echo "No changes to commit"
          git push
